apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: s70xgfh2h-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: s70xgfh2h-python 
  name: s70xgfh2h-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: s70xgfh2h-python 
